# we need super user permission
sudo: required
services:
  - docker

before_install:
  - docker build -t emma/docker-react-v2 -f Dockerfile.dev .

script:
  # -- --coverage ensures test exits after running and not just wait for input interactions
  # for the above, use -e CI=true instead of -- --coverage for travis
  - docker run -e CI=true emma/docker-react-v2 npm run test
